  

  BATCH_SIZE: 1024
  CNN_FM_EMBED_DIM: 128
  CNN_FM_LATENT_DIM: 8 
  DATA_PATH: 'data/' 
  DATA_SHUFFLE: True
  DCN_DROPOUT: 0.2
  DCN_EMBED_DIM: 16
  DCN_MLP_DIMS: (16, 16)
  DCN_NUM_LAYERS: 3
  DEEPCONN_CONV_1D_OUT_DIM: 50
  DEEPCONN_EMBED_DIM: 32
  DEEPCONN_KERNEL_SIZE: 3
  DEEPCONN_LATENT_DIM: 10
  DEEPCONN_OUT_DIM: 32
  DEEPCONN_VECTOR_CREATE: False
  DEEPCONN_WORD_DIM: 768
  DEVICE: 'cuda'
  EPOCHS: 10
  FFM_EMBED_DIM: 16
  FM_EMBED_DIM: 16
  LR: 0.001
  MODEL: None
  NCF_DROPOUT: 0.2
  NCF_EMBED_DIM: 16
  NCF_MLP_DIMS: (16, 16)
  SEED: 42
  TEST_SIZE: 0.2
  WDN_DROPOUT: 0.2
  WDN_EMBED_DIM: 16 
  WDN_MLP_DIMS: (16, 16)
  WEIGHT_DECAY: 1e-06
  WANDB_SWEEP: False
  SPLIT_OPT: tts

